
# Window/tab styling
set -g window-status-separator ' | '
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W '
set -g window-status-current-style 'bg=black,fg=white,bold'
set -g window-status-style 'bg=default,fg=black'

set -g status-left-length 30
set -g status-position bottom

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# tmux-continuum settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# sane scrolling:
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

# Initialize TPM (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
